2025-01-17 16:19:47,069 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\PythonProject\Module_12\tests_12_4.py", line 26, in test_run
    runner = Runner(5)
             ^^^^^^^^^
  File "C:\PythonProject\Module_12\logs.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-17 16:19:47,069 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\PythonProject\Module_12\tests_12_4.py", line 14, in test_walk
    walker = Runner("walker", -5)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\PythonProject\Module_12\logs.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
